name: ci

on:
  push:
    branches: [ "main", "dev" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      configuration: Release
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-quality: 'preview'
          dotnet-version: |
            6.0.x
            8.0.x
            9.0.x

      - name: Restore
        run: dotnet restore

      - name: Build
        run: dotnet build --no-restore -c $configuration

      - name: Run Tests
        run: dotnet test --no-build -c $configuration

      - name: Pack
        run: dotnet pack --no-build -c $configuration -p:VersionMetadata=+${{ github.sha }} --output ./packages

      - name: Upload packages artifact
        uses: actions/upload-artifact@v4
        with:
          name: packages
          path: packages/

  compare_packages:
    runs-on: windows-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-quality: 'preview'
          dotnet-version: |
            9.0.x
  
      - name: Setup NuGet
        uses: nuget/setup-nuget@v2
  
      - name: Install apicompat
        run: dotnet tool install --global Microsoft.DotNet.ApiCompat.Tool
        
      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: packages
          path: packages/
  
      - name: Download Latest NuGet Package for compatibility check
        working-directory: ./compatibility
        run: ./download_latest_packages.ps1
      
      - name: API Compatibility Check
        working-directory: ./compatibility
        run: ./check_compatibility.ps1

  publish:
    runs-on: ubuntu-latest
    needs: compare_packages
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    steps:
      - name: Setup dotnet
        uses: actions/setup-dotnet@v4
        with:
          dotnet-quality: 'preview'
          dotnet-version: |
            9.0.x

      - name: Download artifact
        uses: actions/download-artifact@v4
        with:
          name: packages
          path: packages/

      - name: Publish to NuGet
        run: |
          for package in ./packages/*.nupkg; do
            package_name=$(basename -- "package")
            package_name="${package_name%.*}"
            package_version=$(echo "$package_name" | grep -oP '(\d+)\.(\d+)\.(\d+)(\.\d+)?$')
            package_id=${package_name%.$package_version}
            dotnet nuget delete "$package_id" "$package_version" -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --non-interactive
            dotnet nuget push "$package" -k ${{ secrets.NUGET_API_KEY }} -s https://api.nuget.org/v3/index.json --skip-duplicate
          done
